name: rindexer-erc20-benchmark

volumes:
  rindexer_erc20_pgdata:
    driver: local

services:
  postgresql:
    container_name: rindexer-erc20-postgres
    image: postgres:18
    shm_size: 1g
    restart: always
    volumes:
      - rindexer_erc20_pgdata:/var/lib/postgresql
    ports:
      - 5440:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rindexer}
