# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: erc20-indexer
description: ERC-20 Indexer
contracts:
  - name: ERC20
    events:
      - event: "Approval(address indexed owner, address indexed spender, uint256 value)"
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
chains:
  - id: 1 # Ethereum Mainnet
    start_block: 18600000
    rpc:
      url: ${ENVIO_RPC_URL}
      for: ${ENVIO_RPC_FOR:-fallback}
    contracts:
      - name: ERC20
        address: 0xae78736cd615f374d3085123a210448e74fc6393 # RocketTokenRETH
