[package]
name = "substreams-safe-factory-registrations"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4"
prost = "0.11"
prost-types = "0.11"
substreams = "0.5"
substreams-ethereum = "0.9"
substreams-database-change = "1.3"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
